### ISSUE TITLE
broken indexing for differential_geodesic_endpoint

### ISSUE THREAD

**Issue by wdiepeveen** [JuliaManifolds/Manopt.jl#129] opened 2022-06-06 10:41 UTC
Hi,

Please consider the following

```
pixelM = Sphere(2)
signal_section_size = 2
base = [1.0, 0.0, 0.0]
X = π / 4 * [0.0, 1.0, 0.0]
# Generate a signal with two sections
p1 = exp(pixelM, base, X)
p2 = exp(pixelM, base, -X)
```

For the 1D example
```
f1 = vcat(fill(p1, signal_section_size), fill(p2, signal_section_size))

s1 = size(f1)
M1 = PowerManifold(pixelM, NestedPowerRepresentation(), s1...)

x1 = deepcopy(f1)
m1 = fill(base, size(f1))

Θ1 = get_basis(M1, x1, DefaultOrthonormalBasis())
Mdims1 = prod(manifold_dimension(M1))
e1ⱼ = zeros(Mdims1)
e1ⱼ[1] = 1
Θ1ⱼ = get_vector(M1,m1,e1ⱼ,Θ1)

G1 = differential_geodesic_endpoint(M1, m1, x1, 1 / 2, Θ1ⱼ)
```
this code runs just fine, but for the 2D example
```
f2 = vcat(fill(p1, (signal_section_size, 2* signal_section_size)),
    fill(p2, (signal_section_size, 2* signal_section_size)))


s2 = size(f2)
M2 = PowerManifold(pixelM, NestedPowerRepresentation(), s2...)

x2 = deepcopy(f2)
m2 = fill(base, size(f2))

Θ2 = get_basis(M2, x2, DefaultOrthonormalBasis())
Mdims2 = prod(manifold_dimension(M2))
e2ⱼ = zeros(Mdims2)
e2ⱼ[1] = 1
Θ2ⱼ = get_vector(M2,m2,e2ⱼ,Θ2)

G2 = differential_geodesic_endpoint(M2, m2, x2, 1 / 2, Θ2ⱼ)
```
I get an error
`ERROR: LoadError: ArgumentError: invalid index: PowerManifold(Sphere(2, ℝ), NestedPowerRepresentation(), 4, 4) of type PowerManifold{ℝ, Sphere{2, ℝ}, Tuple{4, 4}, NestedPowerRepresentation}`
Could it be that the indexing is broken for 2D power manifolds?

I'm using Manopt v0.3.24, ManifoldsBase v0.13.7, Manifolds v0.8.7.

**Comment by kellertuer** [comment] 2022-06-06 11:49
We started a small discussion over at base, the short first answer is: Indexing was changed even earlier it seems, I updated the adjoint Jacobi fields but missed to check Jacobi fields (differentials were not yet used much). I will fix this once I have understood (maybe...understood again) why this change was necessary.

So in short: I know where the problem is and we will do a fix soon.

**Comment by kellertuer** [comment] 2022-06-06 12:32
Can you check whether everything works on the new PR branch? I works with your small example, we mainly missed to keep multidimensional Power manifolds and Jacobi fields in mind – this is now fixed :)

**Closed** 2022-06-06 21:23 UTC
